---
abstract: 'add version component to uris'
author:
  - 'Yanick Champoux <yanick@babyl.dyndns.org>'
build_requires:
  Carp: 0
  Catalyst: 0
  Module::Build: 0.3601
  Scalar::Util: 0
  Test::More: 0.94
  Test::WWW::Mechanize::Catalyst: 0
  parent: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102345, CPAN::Meta::Converter version 2.101590'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-VersionedURI
provides:
  Catalyst::Controller::VersionedURI:
    file: lib/Catalyst/Controller/VersionedURI.pm
    version: v1.1.1
  Catalyst::Plugin::VersionedURI:
    file: lib/Catalyst/Plugin/VersionedURI.pm
    version: v1.1.1
requires:
  Catalyst::Controller: 0
  Moose: 0
  Moose::Role: 0
  Path::Class: 0
  URI::QueryParam: 0
  perl: 5.10.0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Catalyst-Plugin-VersionedURI
  homepage: http://search.cpan.org/dist/Catalyst-Plugin-VersionedURI/
  repository: git://github.com/yanick/Catalyst-Plugin-VersionedURI.git
version: 1.1.1
x_authority: cpan:yanick
